FROM maven:3.3.3-jdk-8

# Bundle app source
COPY . /src

# Set the working directory
WORKDIR /src
RUN mkdir /src/target

LABEL test=
LABEL test.run.interval=300000
LABEL test.results=/src/target

CMD ["mvn","clean","install"]

