FROM maven:3.3.3-jdk-8

# Bundle app source
COPY . /src

# Set the working directory
WORKDIR /src

LABEL test=
LABEL test.run.interval=900000
LABEL test.results=/src/results
LABEL test.publish.description="Gaia Integration Tests"

RUN ["mvn","clean","install"]

CMD ["mvn","clean","install"]

